cookies_token_key = 'AT'
cookies_admin_token_key = 'AAT'

string_500 = 'Произошла ошибка при выполнении операции. Обновите страницу и повторите попытку'
string_200 = 'Операция успешно выполнена'
string_403 = 'Доступ запрещен'
string_409 = 'Конфликт'
string_400 = 'Некорректный запрос'
string_404 = 'Не найдено'
string_401 = 'Не авторизован'
string_400_already_authed = 'Уже авторизован'

string_orgs_inn_not_unique = 'ИНН уже используется'
string_orgs_org_not_found = 'Запрашиваемая организация не найдена'
string_orgs_org_not_active = 'Организация не активна'
string_orgs_member_not_found = 'Участник не найден'
string_orgs_member_status_already_set = 'Указан уже установленный статус участника'

string_inv_wrong_expires = 'Указана неверная дата истечения срока действия приглашения'
string_inv_max_invitations = 'Достигнут предел количества активных приглашений'
string_inv_expired = 'Срок действия приглашения истек'
string_inv_not_found = 'Приглашение не найдено'
string_inv_max_usages = 'Приглашение использовано максимальное кол-во раз'
string_inv_owner_error = 'Вы являетесь владельцем этой организации'
string_inv_already_member = 'Вы уже являетесь участником этой организации'
string_inv_blocked_member = 'Вы были заблокированы владельцем организации'

string_storage_max_size = 'Файл слишком большой'
string_storage_wrong_filetype = 'Неверный формат файла'
string_storage_empty_filename = 'Имя файла не указано'
string_storage_saving_error_db = 'Ошибка при информации о файле'
string_storage_empty_file = 'Пустой файл'

string_user_email_exist = 'Указанный адрес электронной почты уже используется'
string_user_username_exist = 'Указанный логин уже используется'
string_user_telnum_exist = 'Указанный номер телефона уже используется'
string_user_telegram_exist = 'Указанный тег Telegram уже используется'
string_user_register_error = 'Ошибка сервера при регистрации пользователя. Обновите страницу и повторите попытку'
string_user_wrong_password = 'Неверный пароль или имя пользователя'
string_user_inactive_user = 'Учетная запись не активна'
string_user_wrong_opw = 'Неверный текущий пароль'
string_user_wrong_npw = 'Новый пароль должен отличаться от старого'

string_product_parsing_error = 'Ошибка при парсинге карточки товара Wildberries'
string_product_parsing_url_error = 'Невозможно определить артикул товара. Проверьте правильность ссылки'
string_product_products_response_error = 'Ошибка получения данных от Wildberries'
string_product_products_response_empty = 'Товары по артикулу не найдены'
string_products_product_not_found = 'Товар не найден'
string_product_size_not_found = 'Размер не найден'
string_product_size_no_barcode = 'Штрих кода размера не указан'
string_product_size_not_active = 'Размер не включен'
string_product_size_not_selected = 'Размер не указан'
string_product_size_no_price = 'Цена не указана или товар не в наличии'

string_product_size_not_in_stock = 'Размер товара не в наличии'
string_product_product_not_in_stock = 'Товар не в наличии'
string_product_multiple_sizes_error = 'Укажите размер товара (товар имеет несколько размеров)'
string_product_size_not_selected_but_match = 'Размер не указан'
string_product_too_many_files = 'Максимальное количество файлов 5'
string_product_refresh_error = 'Обновлять товар можно не чаще чем 1 раз в 5 минут'
string_products_product_already_exists = 'Ошибка при добавлении нового товара. Код красный'

string_orders_time_error = 'Задачи на текущие сутки регистрируются до 9:00. Пожалуйста, выберите один из следующих дней'
string_orders_max_amount = 'Количество задач, добавляемое за один раз должно быть не более 100'
string_orders_size_not_in_stock = 'Выбранный размер или товар не в наличии'
string_orders_wrong_date = 'Нельзя планировать выкупы на дни, раньше текущего'
string_orders_already_paid = 'Задача уже оплачена'
string_orders_old_to_pay = 'Нельзя оплатить задачу за прошедшее время'
string_orders_no_orders_to_pay = 'Задачи не выбраны'
string_orders_task_not_found = 'Задача не найдена'
string_products_max_tasks_per_day = 'Максимальное кол-во задач, планируемое на 1 день равно 500'

string_payments_no_levels = 'Схема расчета платежей не найдена'
string_payments_not_enough_balance = 'Недостаточно средств на кошельке'
string_payments_wrong_date = 'Нельзя оплачивать задачи на дни, раньше текущего'
